#ifndef ENUMERATORS_H__
#define ENUMERATORS_H__

enum IMAGE
{
	CUSTIMAGE_BLACK_BACK,
	CUSTIMAGE_BOO,
	CUSTIMAGE_RUN,
	CUSTIMAGE_CROSSHAIR,
	CUSTIMAGE_INTERFACE_FRAME,
	CUSTIMAGE_PORTRAIT_FRAME,
	CUSTIMAGE_PORTRAIT_MALE,
	CUSTIMAGE_PGBTEXT_HEALTH,
	CUSTIMAGE_PGBTEXT_HEALTH_BACK,
	CUSTIMAGE_PGBTEXT_HEALTH_LOW,
	CUSTIMAGE_PGBTEXT_ENERGY,
	CUSTIMAGE_PGBTEXT_ENERGY_BACK,
	CUSTIMAGE_PGBTEXT_MANA,
	CUSTIMAGE_PGBTEXT_MANA_BACK,
	CUSTIMAGE_PGBTEXT_EXP,
	CUSTIMAGE_PGBTEXT_EXP_BACK,
	CUSTIMAGE_CONSOLE_BACK,
	CUSTIMAGE_CONSOLE_TEXTBOX_BACK,
	CUSTIMAGE_CLOCK_BG,
	CUSTIMAGE_PERSONAL_CURSOR,
	CUSTIMAGE_LOADING_SCREEN,
	CUSTIMAGE_MENU_BACKGROUND,
	CUSTIMAGE_MENU_MAIN_WINDOW,
	CUSTIMAGE_MENU_BUTTON_BACK,
	CUSTIMAGE_MENU_LOGO,
	CUSTIMAGE_WELCOME_FACE,
	CUSTIMAGE_ARROWBUTTON_UP,
	CUSTIMAGE_ARROWBUTTON_DOWN,
	CUSTIMAGE_LAST
};

enum SPELL_IMAGE
{
	SPELL_IMAGE_BOLT,
	SPELL_IMAGE_FIRE,
	SPELL_IMAGE_FREEZE,
	SPELL_IMAGE_SHOCK,
	SPELL_IMAGE_POISON,
	SPELL_IMAGE_STORM,
	SPELL_IMAGE_HEAL,
	SPELL_IMAGE_RAIN,
	SPELL_IMAGE_DEFEND,
	SPELL_IMAGE_SHIELD

};

/**
* Palette de couleurs possibles pour le texte
*/
enum COLOR
{
	TEXTCOLOR_WHITE,
	TEXTCOLOR_RED,
	TEXTCOLOR_GREEN,
	TEXTCOLOR_BLUE,
	TEXTCOLOR_YELLOW,
	TEXTCOLOR_LAST
};


enum CONTROLTYPE
{
	CTRLTYPE_NONE,
	CTRLTYPE_PROGRESSBAR,
	CTRLTYPE_LABEL,
	CTRLTYPE_BOUTON,
	CTRLTYPE_SPELLBUTTON,
	CTRLTYPE_PICTUREBOX,
	CTRLTYPE_PANEL,
	CTRLTYPE_LISTBOX,
	CTRLTYPE_TEXTBOX,
	CTRLTYPE_BUBBLE,
	CTRLTYPE_WINDOW,
	CTRLTYPE_DIALOGBOX,
	CTRLTYPE_TIMER
};
enum BLENDTYPE
{
	CBLEND_NONE,
	CBLEND_PNG,
	CBLEND_BLUR
};

enum ORIGIN
{
	ORIGIN_BOTTOMLEFT,
	ORIGIN_BOTTOMRIGHT,
	ORIGIN_TOPLEFT,
	ORIGIN_TOPRIGHT
};

/**
* Affichera le texte à l'endroit spécifié par rapport au conteneur
*/
enum Docking
{
	TEXTDOCK_NONE,
	TEXTDOCK_TOPLEFT,
	TEXTDOCK_TOPCENTER,
	TEXTDOCK_TOPRIGHT,
	TEXTDOCK_MIDDLELEFT,
	TEXTDOCK_MIDDLECENTER,
	TEXTDOCK_MIDDLERIGHT,
	TEXTDOCK_BOTTOMLEFT,
	TEXTDOCK_BOTTOMCENTER,
	TEXTDOCK_BOTTOMRIGHT,
	TEXTDOCK_LAST
};

enum Imageformat
{
	IMAGEFORMAT_STRETCH,
	IMAGEFORMAT_FIT,
	IMAGEFORMAT_TILE
};

enum ThemeSet
{
	THEME_MAINMENU,
	THEME_DEFAULT_INTERFACE,
	THEME_DEFAULT,
	THEME_PLAYER_VALUES,
	THEME_CONSOLE,
	THEME_LAST
};



#endif