#ifndef NPCINFO_H_
#define NPCINFO_H_

#include "define.h"

#define MONSTER_MAX_NUMBER			30

//Noms de models
#define NPC_PIG_MODEL			MODEL_PATH_ANIMALS_GRD "pig.lcm"
#define NPC_PIG_LEVEL			1
#define NPC_PIG_HEALTH			50

#define NPC_BWIDOW_MODEL		MODEL_PATH_ANIMALS_GRD "bwidow.lcm"
#define NPC_BWIDOW_LEVEL		2
#define NPC_BWIDOW_HEALTH		75

#define NPC_ARACHNID_MODEL		MODEL_PATH_ANIMALS_GRD "arachnid.lcm"
#define NPC_ARACHNID_LEVEL		8
#define NPC_ARACHNID_HEALTH		250

#define NPC_RHINO_MODEL			MODEL_PATH_ANIMALS_GRD "rhino.lcm"
#define NPC_RHINO_LEVEL			4
#define NPC_RHINO_HEALTH		130

#define NPC_ARMDILLO_MODEL		MODEL_PATH_ANIMALS_GRD "armdillo.lcm"
#define NPC_ARMDILLO_LEVEL		1
#define NPC_ARMDILLO_HEALTH		50

#define NPC_DEER_M_MODEL		MODEL_PATH_ANIMALS_GRD "deer_m.lcm"
#define NPC_DEER_M_LEVEL		2
#define NPC_DEER_M_HEALTH		80

#define NPC_COYOTE_MODEL		MODEL_PATH_ANIMALS_GRD "coyote.lcm"
#define NPC_COYOTE_LEVEL		3
#define NPC_COYOTE_HEALTH		90

#define NPC_DONKEY_MODEL		MODEL_PATH_ANIMALS_GRD "donkey.lcm"
#define NPC_DONKEY_LEVEL		2
#define NPC_DONKEY_HEALTH		70

#define NPC_HUSKY_MODEL			MODEL_PATH_ANIMALS_GRD "husky.lcm"
#define NPC_HUSKY_LEVEL			5
#define NPC_HUSKY_HEALTH		160

#define NPC_HYENA_MODEL			MODEL_PATH_ANIMALS_GRD "hyena.lcm"
#define NPC_HYENA_LEVEL			6
#define NPC_HYENA_HEALTH		160

#define NPC_REDFOX_MODEL		MODEL_PATH_ANIMALS_GRD "redfox.lcm"
#define NPC_REDFOX_LEVEL		4
#define NPC_REDFOX_HEALTH		110

#define NPC_SHEEP_MODEL			MODEL_PATH_ANIMALS_GRD "sheep.lcm"
#define NPC_SHEEP_LEVEL			1
#define NPC_SHEEP_HEALTH		40

#define NPC_CATBLK_MODEL		MODEL_PATH_ANIMALS_GRD "catblk.lcm"
#define NPC_CATBLK_LEVEL		2
#define NPC_CATBLK_HEALTH		60

#define NPC_BISON_MODEL			MODEL_PATH_ANIMALS_GRD "bison.lcm"
#define NPC_BISON_LEVEL			7
#define NPC_BISON_HEALTH		240

#define NPC_TORTOISE_MODEL		MODEL_PATH_ANIMALS_GRD "tortoise.lcm"
#define NPC_TORTOISE_LEVEL		5
#define NPC_TORTOISE_HEALTH		190

#define NPC_ALLIGATR_MODEL		MODEL_PATH_ANIMALS_GRD "alligatr.lcm"
#define NPC_ALLIGATR_LEVEL		8
#define NPC_ALLIGATR_HEALTH		220

#define NPC_TRANTULA_MODEL		MODEL_PATH_ANIMALS_GRD "trantula.lcm"
#define NPC_TRANTULA_LEVEL		6
#define NPC_TRANTULA_HEALTH		180

#define NPC_SCORPION_MODEL		MODEL_PATH_ANIMALS_GRD "scorpion.lcm"
#define NPC_SCORPION_LEVEL		5
#define NPC_SCORPION_HEALTH		160


#define NPC_MONARCH_MODEL		MODEL_PATH_ANIMALS_AIR "monarch.lcm"
#define NPC_MONARCH_LEVEL		1
#define NPC_MONARCH_HEALTH		20



#endif